# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-02 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredrca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='diciplinas',
            field=models.ManyToManyField(blank=True, null=True, to='coredrca.Disciplina'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='obr_let',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='nome',
            field=models.CharField(max_length=300),
        ),
    ]
